import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import Link from "next/link";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={inter.className}>
        {/* <div>
          <nav>
          <ul className="flex row gap-10" >
          <Link href={'/addBook'}>Add Details</Link>
          <Link href={'/bookList'}>Book List</Link>
          </ul>
          </nav>
        </div> */}
        {children}</body>
    </html>
  );
}
